name: Build windows exe with PyInstaller

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: ./

      - uses: actions/upload-artifact@main
        with:
          name: gdc_vols
          path: dist/windows
